In [1]:
import sys
import os
sys.path.append('/work/benyamin/smollm/Kangaroo')


from transformers import AutoModelForCausalLM
from transformers_extra import *
from kangaroo.kangaroo_model import KangarooModel

/home/benyamin/miniconda3/envs/smol/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model = AutoModelForCausalLM.from_pretrained("/work/benyamin/smollm/hf_checkpoints/Smollm_1B_Frozen_Sorted_Balcony")


In [14]:
model.state_dict()

In [8]:
from collections import OrderedDict
from transformers import LlamaConfig
from kangaroo.adapter import AdapterModel
import torch
from kangaroo.kangaroo_model import KangarooModel
class arguments:
    dtype='bfloat16'

model = KangarooModel(
    model_name_or_path='/work/benyamin/smollm/hf_checkpoints/Smollm_1B_Frozen_Sorted_Balcony',
    args=arguments(),
    EARLY_STOP_LAYER=4
)

model.save_pretrained('./temp/')

# final_state = OrderedDict()
# states = model.model.exit_modules[0].state_dict()
# for k, v in states.items():
#     if k[0] == '0':
#         final_state['layers.' + k] = v
#     if k[0] == '1':
#         final_state['norm.weight'] = v
# # print(final_state)
# adapter_model_path = '/work/benyamin/smollm/hf_checkpoints/Smollm_1B_Frozen_Sorted_Balcony'
# config = LlamaConfig.from_pretrained(os.path.join(adapter_model_path, "config.json"), num_hidden_layers=1)

# adapter_model = AdapterModel(config, balcony=True)

# adapter_model.load_state_dict(final_state, strict=True)


You are using a model of type nested_llama to instantiate a model of type llama. This is not supported for all configurations of models and can yield errors.
You are using a model of type nested_llama to instantiate a model of type llama. This is not supported for all configurations of models and can yield errors.
You are using a model of type nested_llama to instantiate a model of type llama. This is not supported for all configurations of models and can yield errors.


AttributeError: 'KangarooModel' object has no attribute 'save_pretrained'

In [17]:
from accelerate import Accelerator
accelerator = Accelerator(mixed_precision='fp16')
model = accelerator.prepare(model.adapter_model)
accelerator.save_state('./temp', safe_serialization=False)

PosixPath('temp')

In [10]:
class arguments:
    dtype = 'bfloat16'

args = arguments()
# args.dtype
KangarooModel('/work/benyamin/smollm/hf_checkpoints/Smollm_1B_Frozen_Sorted_Balcony',
              '/work/benyamin/smollm/hf_checkpoints/Smollm_1B_Frozen_Sorted_Balcony',
              args, EARLY_STOP_LAYER = 4)

In [18]:
import torch
ckpt = torch.load('/work/benyamin/smollm/Kangaroo/balcony/temp/pytorch_model.bin')

In [19]:
ckpt

OrderedDict([('norm.weight',
              tensor([1.0547, 1.1016, 1.0234,  ..., 1.0312, 1.0547, 1.0859], device='cuda:0')),
             ('layers.0.self_attn.q_proj.weight',
              tensor([[ 0.0002,  0.0015,  0.0220,  ...,  0.0170, -0.0028,  0.0025],
                      [-0.0075,  0.0073,  0.0085,  ...,  0.0019,  0.0070, -0.0103],
                      [ 0.0043,  0.0015, -0.0172,  ...,  0.0038,  0.0097,  0.0256],
                      ...,
                      [-0.0002,  0.0039,  0.0118,  ...,  0.0281, -0.0226, -0.0361],
                      [-0.0058,  0.0249,  0.0233,  ...,  0.0432,  0.0137, -0.0086],
                      [ 0.0311,  0.0093,  0.0087,  ..., -0.0107, -0.0160, -0.0256]],
                     device='cuda:0')),
             ('layers.0.self_attn.k_proj.weight',
              tensor([[ 0.0084, -0.0059,  0.0011,  ...,  0.0099, -0.0014,  0.0142],
                      [ 0.0002,  0.0255,  0.0018,  ...,  0.0082, -0.0228, -0.0139],
                      [-0.0071, -0.

: 